name: Build and Push Images

on:
  workflow_dispatch:

env:
  REGISTRY_LOCATION: europe-west1
  REGISTRY_NAME: agents
  ENVIRONMENT: prd

jobs:
  validation:
    name: Code Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install validation dependencies
      run: pip install pyyaml black
    
    - name: Check code formatting
      run: black --check agents/ shared/
    
    - name: Validate YAML files
      run: |
        python -c "import yaml; yaml.safe_load(open('agents_config.yaml'))"
        python -c "import yaml; yaml.safe_load(open('docker-compose.yml'))"

  build-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: validation
    
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Discover agents
      id: discover
      run: |
        AGENTS_DIR="agents"
        agents=()
        
        for dir in "$AGENTS_DIR"/*/ ; do
            if [ -f "${dir}Dockerfile" ]; then
                agent_name=$(basename "$dir")
                agents+=("\"$agent_name\"")
            fi
        done
        
        agents_json=$(IFS=,; echo "${agents[*]}")
        matrix_json="{\"agent\": [$agents_json]}"
        
        echo "matrix=$matrix_json" >> $GITHUB_OUTPUT
        echo "Discovered agents: $matrix_json"
    
    - name: Detect changed agents
      id: changes
      run: |
        # Jeśli to pierwszy build, zbuduj wszystkich
        if ! git rev-parse HEAD~1 >/dev/null 2>&1; then
          echo "First build - building all agents"
          echo "changed_agents=$(echo '${{ steps.discover.outputs.matrix }}' | jq -c '.agent')" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Sprawdź które foldery się zmieniły od ostatniego commita
        CHANGED_DIRS=$(git diff --name-only HEAD~1 HEAD | grep '^agents/' | cut -d'/' -f2 | sort -u)
        
        # Sprawdź czy zmieniły się shared/ lub agents_config.yaml (wtedy buduj wszystkich)
        if git diff --name-only HEAD~1 HEAD | grep -E '^(shared/|agents_config.yaml)'; then
          echo "Shared files changed - building all agents"
          echo "changed_agents=$(echo '${{ steps.discover.outputs.matrix }}' | jq -c '.agent')" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        # Lista zmienionych agentów
        changed_agents=()
        for dir in $CHANGED_DIRS; do
          if [ -d "agents/$dir" ] && [ -f "agents/$dir/Dockerfile" ]; then
            changed_agents+=("\"$dir\"")
          fi
        done
        
        if [ ${#changed_agents[@]} -eq 0 ]; then
          echo "No agents changed - nothing to build"
          echo "changed_agents=[]" >> $GITHUB_OUTPUT
        else
          agents_json=$(IFS=,; echo "${changed_agents[*]}")
          echo "changed_agents=[$agents_json]" >> $GITHUB_OUTPUT
          echo "Changed agents: [$agents_json]"
        fi
    
    - name: Debug secrets
      run: |
        echo "WIF_PROVIDER exists: ${{ secrets.WIF_PROVIDER != '' }}"
        echo "WIF_SERVICE_ACCOUNT exists: ${{ secrets.WIF_SERVICE_ACCOUNT != '' }}"
        echo "GCP_PROJECT_ID exists: ${{ secrets.GCP_PROJECT_ID != '' }}"
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      id: auth
      with:
        workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
        service_account: ${{ secrets.WIF_SERVICE_ACCOUNT }}
    
    - name: Set project
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Verify authentication
      run: |
        echo "Checking authentication..."
        gcloud auth list
        echo "Current account:"
        gcloud config get-value account
        echo "Current project:"
        gcloud config get-value project
    
    - name: Configure Docker
      run: gcloud auth configure-docker ${{ env.REGISTRY_LOCATION }}-docker.pkg.dev
    
    - name: Set image tags
      id: tags
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        echo "short_sha=${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "timestamp=${TIMESTAMP}" >> $GITHUB_OUTPUT
    
    - name: Build and push all agents
      run: |
        AGENTS=$(echo '${{ steps.changes.outputs.changed_agents }}' | jq -r '.[]')
        
        if [ -z "$AGENTS" ]; then
          echo "No agents to build - skipping"
          exit 0
        fi
        
        for AGENT in $AGENTS; do
          echo "Building $AGENT..."
          
          IMAGE_BASE="${{ env.REGISTRY_LOCATION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REGISTRY_NAME }}/$AGENT"
          
          docker build \
            -t ${IMAGE_BASE}:${{ steps.tags.outputs.short_sha }} \
            -t ${IMAGE_BASE}:${{ steps.tags.outputs.timestamp }} \
            -t ${IMAGE_BASE}:${{ env.ENVIRONMENT }} \
            -t ${IMAGE_BASE}:latest \
            -f agents/$AGENT/Dockerfile \
            .
          
          echo "Pushing $AGENT..."
          docker push ${IMAGE_BASE}:${{ steps.tags.outputs.short_sha }}
          docker push ${IMAGE_BASE}:${{ steps.tags.outputs.timestamp }}
          docker push ${IMAGE_BASE}:${{ env.ENVIRONMENT }}
          docker push ${IMAGE_BASE}:latest
          
          echo "Completed $AGENT"
        done
    
    - name: Build summary
      run: |
        AGENTS=$(echo '${{ steps.changes.outputs.changed_agents }}' | jq -r '.[]')
        
        echo "### Build Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Environment: ${{ env.ENVIRONMENT }}" >> $GITHUB_STEP_SUMMARY
        echo "SHA: ${{ steps.tags.outputs.short_sha }}" >> $GITHUB_STEP_SUMMARY
        echo "Timestamp: ${{ steps.tags.outputs.timestamp }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -z "$AGENTS" ]; then
          echo "**No agents changed - nothing built**" >> $GITHUB_STEP_SUMMARY
        else
          echo "#### Built agents:" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.changes.outputs.changed_agents }}' | jq -r '.[]' | while read agent; do
            echo "- $agent" >> $GITHUB_STEP_SUMMARY
          done
        fi

  summary:
    name: Pipeline Summary
    runs-on: ubuntu-latest
    needs: [validation, build-push]
    if: always()
    
    steps:
    - name: Generate summary
      run: |
        echo "## Pipeline Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "| Stage | Status |" >> $GITHUB_STEP_SUMMARY
        echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
        echo "| Validation | ${{ needs.validation.result }} |" >> $GITHUB_STEP_SUMMARY
        echo "| Build & Push | ${{ needs.build-push.result }} |" >> $GITHUB_STEP_SUMMARY